### ISSUE TITLE
Help needed - how to use

### ISSUE THREAD

**Issue by rlueckl** [rundeck-plugins/attribute-match-node-enhancer#1]
Hi,

we are trying to use this node enhancer in our setup, but it doesn't seem to do anything. We've put `attribute-match-node-enhancer-0.1.3.jar` under `/var/lib/rundeck/libext`, restarted Rundeck. Now we can define an "Attribute Match" under Project Settings -> Edit Nodes -> Enhancers.

![enhancer](https://user-images.githubusercontent.com/10848041/58423016-66386d80-8094-11e9-9f9d-6e5a977e59e8.png)

Unfortunately the new attribute doesn't show up, when we are searching for the node. (Only the previously defined attributes are visible.)

Nodes are defined with the "URL Source" option and look like this:

![rundeck_node](https://user-images.githubusercontent.com/10848041/58423221-d941e400-8094-11e9-8b1b-205d1a7f8629.png)

As you can see, the attribute **stage** is defined as _qa_, so the Attribute Match should match and add the **test_attribute**.

Unfortunately we don't see any errors in the logs or even if the Attribute Match worked or not...

Can you please help?

**Comment by gschueler** [comment]
I could not reproduce this issue on the latest version of rundeck, can you try with Rundeck 3.3.x?

**Comment by rlueckl** [comment]
We had Rundeck 3.0.xx before and it wasn't working.

Currently we use Rundeck 3.2.8 and it's fine. So I guess it was fixed sometime in between.

Thanks!
