### ISSUE TITLE
Poor readibility due to Markdown not supported

### ISSUE THREAD

**Issue by arturmartins** [rundeck-plugins/attribute-match-node-enhancer#4]
Check how the help text is rendered below the first textarea:

![Screenshot 2020-04-17 at 00 38 47](https://user-images.githubusercontent.com/101411/79516628-d43aaa00-8043-11ea-8b73-e5080d8629d0.png)

# How it should look like: 
---

Attribute name/values to match. All matches must be met to add the additional attributes. Each entry should be of the form: 

* `key` `operator` `value` 

Where `key` is the attribute name, `operator` is one of:

* `==` equality match 
* `!!` not present match 
* `=~` regular expression match 
* `!=` inequality match 
* `!~` negative regular expression match 

---

https://github.com/rundeck-plugins/attribute-match-node-enhancer/blob/fffc024fba47bed0d31c80dd3d9ef29061ae94e8/src/main/java/org/rundeck/plugins/nodes/attributes/AttributeNodeEnhancer.java#L29

This might help with #1

**Comment by gschueler** [comment]
@arturmartins thanks, I think this is a rundeck issue, as markdown is supported for other types of plugins in the plugin property descriptions.  I will transfer this issue to rundeck/rundeck

**Comment by arturmartins** [comment]
Thanks, @gschueler. Should this issue be closed then?
